### ISSUE TITLE
[Bug] Cannot find module '/usr/local/lib/node_modules/stream/promises'

### ISSUE THREAD

**Issue by longfeiWan9** [nftstorage/carbites-cli#4]
Env:

- MacOS Monterey Intel 
- Nodejs: v14.17.6

After installing carbites-cli by running `npm install -g carbites-cli`, then it throws errors when I run  `carbites --help`. 

the errors is:
```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/usr/local/lib/node_modules/stream/promises' imported from /usr/local/lib/node_modules/carbites-cli/bin/carbites.js
    at finalizeResolution (internal/modules/esm/resolve.js:285:11)
    at moduleResolve (internal/modules/esm/resolve.js:708:10)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:819:11)
    at Loader.resolve (internal/modules/esm/loader.js:89:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:242:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:73:40)
    at link (internal/modules/esm/module_job.js:72:36) {
  code: 'ERR_MODULE_NOT_FOUND'
  ```
  Any suggestions on what is missing?

**Comment by elhadede** [comment]
how did you solved it?
